### PR TITLE
feat: theme toggle

### LINKED ISSUE #22: As a user, I should be able to toggle between light/dark mode

### PR DESCRIPTION
**Pull request by diaasaur**
Close issue #22 with these changes:
- ThemeContext:
  - `prefersDarkMode` detects user's system preference for light/dark mode
  - theme will be determined by checking localStorage, if empty defaults to the preferred mode
  - theme is applied to `document.documentElement` or the root with `data-theme`
  - toggleTheme function toggles between `light` and `dark` mode.
  - added a `useTheme` hook to consume ThemeContext easily
- css reset to normalize default styles for consistent rendering across browsers.
- introduced a variables.css file to define theme colors (and a place for other variables in future).
- added a fonts.css file to import and configure fonts.
- added `Inter` (variable) font.
- added `react-icons` to provide a convenient way to include and customize SVG icons.
- ThemeToggle component: A button with Moon (dark) and Sun (light) icons which toggles the theme onClick

note: added `eslint-config-prettier` to pick prettier over eslint for formatting (letting prettier do code formatting and eslint handle the remaining issues) 

this ended up being a large PR 😭, in the future I'll try to ask for incremental reviews for a feature :D

### CODE REVIEW

**Review by Sumitgangwar58 — COMMENTED** [review]
There are some warnings of eslint
Hint: Use single quote for strings

**Comment by diaasaur** [comment]
yeah I just noticed, rebased into the new eslint rules and they are fucking me up 💀 looking into it

**Comment by diaasaur** [comment]
why didn't husky detect these ESLint errors? 

my 2 cents: husky's pre-commit hook + lint-staged run linters on files that have been staged for commit. when i rebased into the updated main, the only changes that were commited were related to package.json (which didn't trigger any ESLint errors). this might be a good usecase for having linter checks at pr-level but i doubt we will get this problem again :3

**Comment by DikshantAgarwal** [comment]
> why didn't husky detect these ESLint errors?
> 
> my 2 cents: husky's pre-commit hook + lint-staged run linters on files that have been staged for commit. when i rebased into the updated main, the only changes that were commited were related to package.json (which didn't trigger any ESLint errors). this might be a good usecase for having linter checks at pr-level but i doubt we will get this problem again :3

Have you installed Eslint extensions on your VS code. Most of the eslint issues will be autofix by that

**Comment by diaasaur** [comment]
#> > why didn't husky detect these ESLint errors?
> > my 2 cents: husky's pre-commit hook + lint-staged run linters on files that have been staged for commit. when i rebased into the updated main, the only changes that were commited were related to package.json (which didn't trigger any ESLint errors). this might be a good usecase for having linter checks at pr-level but i doubt we will get this problem again :3
> 
> Have you installed Eslint extensions on your VS code. Most of the eslint issues will be autofix by that

yes I do have it!

would the extension even detect these errors if the respective files were never opened 🤔? my flow yesterday was, rebase, push to remote and open a pr - and what sumit noticed was just the tip of the iceberg, there were more eslint errors (not formatting related) after I ran `npm run lint:code` instead of checking every file to see if there is any error or not.

husky was added in the first place to not let errors like this slip through, that was why I was explaining why husky did not work in this case

btw I hope it was clear why I added [eslint-config-prettier](https://prettier.io/docs/en/integrating-with-linters.html) [another reference](https://stackoverflow.com/a/44690309)

you can check my recent commits to get an idea of what was changed

**Review by Sumitgangwar58 — APPROVED** [review]

**Pull request merged**
